# templates/route.yaml

apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "spring-boot.fullname" . }}
spec:
  host:
  to:
    kind: Service
    name: {{ include "spring-boot.fullname" . }}
    weight: 100
  port:
    targetPort: {{ .Values.service.port }}
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Allow
  wildcardPolicy: None
